version: "3.8"

services:

  database:
    container_name: database
    restart: unless-stopped
    env_file: ./database/.env
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - database:/var/lib/mysql
      - ./database/src:/docker-entrypoint-initdb.d

volumes:
  database:
    driver: local