version: "3.8"

services:

  database:
    container_name: database
    build: ./database
    env_file: ./database/.env
    ports:
      - "3306:3306"
    volumes:
      - ./database/src:/docker-entrypoint-initdb.d