name: fivex

services:

  database:
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: fivex
    ports:
      - "3306:3306"
    volumes:
      - database:/var/lib/mysql
      - ./database/script.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - fivex-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - fivex-network

networks:
  fivex-network:
    name: fivex-network
    driver: bridge

volumes:
  database:
    name: database
