version: "3.8"

services:

  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: database
    ports:
      - "3306:3306"
    env_file:
      - ./database/.env
    volumes:
      - ./database/src:/docker-entrypoint-initdb.d